#!/bin/env ruby
# encoding: utf-8
puts "The students of my cohort at Makers Academy"
puts "-------------------------------------------"
puts "Javier Silverio"
puts "Elliot Lewis"
puts "Ben Tillett"
puts "Vincent Koch"
puts "Michelle Ballard"
puts "Nick Robets"
puts "Tatjana Soukiassian"
puts "Mervé Silk"
puts "Albert Vallverdu"
puts "Lovis Schultze"
puts "Henry Stanley"
puts "Spike Lindsey"
puts "Ruth Earle"
puts "Andy Gates"
puts "Faisal Aydarus"
puts "Ethel Ng"
puts "Kevin Daniells"
puts "Leopold Kwok"
puts "James McNeil"
puts "Jerome Pratt"
puts "Chris Oatley"
puts "Marc Singh"
print "overall we have "
print 24
print " great students"